apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: alpine
      image: alpine
      command: ["/bin/sh","-c"]
      args: ["shuf -i 1-100 -n 3 >> /opt/vishnu.txt;"]
      volumeMounts:
        - mountPath: /opt
          name: data-volume
  volumes:
    - name: data-volume
      hostPath:
        path: /root
        type: Directory
